### ISSUE TITLE
Date being reseted to 01/01/1970 insread of now

### ISSUE THREAD

**Issue by cosiluancosta** [k35o/storybook-addon-mock-date#6]
<img width="524" alt="image" src="https://github.com/k35o/storybook-addon-mock-date/assets/81383365/cf393669-580d-4fb2-8cfa-3bf1f842e530">

After installing the addon, when my component uses `new Date()` it returns 01/01/1970  
(bc of my timezone -3, it goes to 12/31/1969) 

In my `Story` file the `parameters: {}` object is empty.

**Comment by k35o** [comment]
@cosiluancosta 
Thanks for the bug report.
I fixed it with an #7.

fixed in storybook-addon-mock-date@0.5.
